### ISSUE TITLE
0.7 git tag

### ISSUE THREAD

**Issue by micwoj92** [dakk/FreeAlchemist#1]
Hello, is it possible to add 0.7 here? Thanks.
https://github.com/dakk/FreeAlchemist/tags

**Comment by dakk** [comment]
Sure, done: https://github.com/dakk/FreeAlchemist/releases/tag/v0.7

Can I ask you why do you need it?

**Comment by micwoj92** [comment]
Thanks
It's easier to specify tag than a commit if you package this.
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=freealchemist#n13

It's also easier to check for new releases this way when using tools such as nvchecker.
